version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: 4s8SD4kjs904ow

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc123.
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  python:
    image: python
    restart: always
    ports:
      - 5000:5000
    command:
      - /usr/bin/bash
      - /web/run.sh
    working_dir: /web
    volumes:
      - ./src:/web
    